from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_ROOT = PROJECT_ROOT / "outputs" / "demo_snapshot"
VISUAL_IMAGE_DIR = PROJECT_ROOT / "assets" / "test_sequences" / "bedroom_sequence"


def main() -> int:
    _reset_dir(SNAPSHOT_ROOT)
    local_dir = SNAPSHOT_ROOT / "local_sim_track1_demo"
    visual_dir = SNAPSHOT_ROOT / "visual_evidence_demo"
    local_dir.mkdir(parents=True, exist_ok=True)
    visual_dir.mkdir(parents=True, exist_ok=True)

    local_command = [
        sys.executable,
        "-m",
        "harness.run_track1",
        "--env",
        "local_sim",
        "--episode-id",
        "local-explore-book-relocated",
        "--output-dir",
        str(local_dir),
        "--validate",
        "--mock",
    ]
    _run(local_command)

    if len(_frames(VISUAL_IMAGE_DIR)) < 2:
        raise SystemExit(
            "Visual evidence demo requires local frame images under "
            f"{VISUAL_IMAGE_DIR}. Add frame_000.jpg/png, frame_001.jpg/png, ..."
        )
    visual_command = [
        sys.executable,
        "-m",
        "harness.run_visual_demo",
        "--frames",
        str(VISUAL_IMAGE_DIR),
        "--max-frames",
        "3",
        "--visual-task",
        "Is the laptop on the chair?",
        "--output-dir",
        str(visual_dir),
        "--validate",
        "--mock",
    ]
    _run(visual_command)

    _write_readme(local_command, visual_command)
    _check_expected(
        local_dir,
        ["world_model.json", "episode_log.jsonl", "run_audit.json", "harness_result.json", "track1_score.json"],
    )
    _check_expected(
        visual_dir,
        [
            "world_model.json",
            "episode_log.jsonl",
            "run_audit.json",
            "harness_result.json",
            "visual_task_result.json",
        ],
    )
    print(f"Demo snapshot written to {SNAPSHOT_ROOT}")
    return 0


def _run(command: list[str]) -> None:
    print(f"\n$ {' '.join(command)}", flush=True)
    completed = subprocess.run(command, cwd=PROJECT_ROOT)
    if completed.returncode != 0:
        raise SystemExit(completed.returncode)


def _reset_dir(path: Path) -> None:
    if path.exists():
        resolved = path.resolve()
        project_outputs = (PROJECT_ROOT / "outputs").resolve()
        if project_outputs not in resolved.parents and resolved != project_outputs:
            raise SystemExit(f"Refusing to remove unexpected path: {resolved}")
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def _frames(image_dir: Path) -> list[Path]:
    if not image_dir.exists() or not image_dir.is_dir():
        return []
    return sorted(
        [
            path
            for path in image_dir.iterdir()
            if path.is_file()
            and path.name.lower().startswith("frame_")
            and path.suffix.lower() in {".jpg", ".jpeg", ".png", ".webp"}
        ],
        key=lambda path: path.name.lower(),
    )


def _check_expected(directory: Path, names: list[str]) -> None:
    missing = [name for name in names if not (directory / name).exists()]
    if missing:
        raise SystemExit(f"Demo snapshot missing files in {directory}: {', '.join(missing)}")


def _write_readme(local_command: list[str], visual_command: list[str]) -> None:
    del local_command, visual_command
    local_repro = (
        "python -m harness.run_track1 --env local_sim "
        "--episode-id local-explore-book-relocated "
        "--output-dir outputs/demo_snapshot/local_sim_track1_demo --validate --mock"
    )
    visual_repro = (
        "python -m harness.run_visual_demo --frames assets/test_sequences/bedroom_sequence "
        "--max-frames 3 --visual-task \"Is the laptop on the chair?\" "
        "--output-dir outputs/demo_snapshot/visual_evidence_demo --validate --mock"
    )
    text = f"""# Demo Snapshot

This directory contains a reproducible local demo snapshot for the EAGC Track 1 MVP.

It is generated by:

```powershell
python tools/create_demo_snapshot.py
```

## LocalSim Track 1 Demo

Directory: `local_sim_track1_demo/`

Included artifacts:

- `world_model.json`
- `episode_log.jsonl`
- `run_audit.json`
- `harness_result.json`
- `track1_score.json`
- `generated_episode_spec.json` if generated by the selected run

Reproduction command:

```powershell
{local_repro}
```

## Visual Evidence Demo

Directory: `visual_evidence_demo/`

Included artifacts:

- `world_model.json`
- `episode_log.jsonl`
- `run_audit.json`
- `harness_result.json`
- `visual_task_result.json`
- `qwen_response_summary.json` if the selected run used the real local vLLM path

Reproduction command:

```powershell
{visual_repro}
```

The visual evidence demo uses local frame images from `assets/test_sequences/bedroom_sequence/`.
Those image files are smoke-test resources and are not tracked in git.

## Scope

This snapshot is a local MVP demonstration. It is not an official EAGC runtime result,
not ProcTHOR/AI2-THOR, and not a training run.
"""
    (SNAPSHOT_ROOT / "README_demo.md").write_text(text, encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
